services:
  fc-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: fc-rabbitmq
    networks:
      - notificationsNet
    ports:
      - ${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}
    env_file:
      - ./.env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./.volumes/rabbitmq:/var/lib/rabbitmq/mnesia
    restart: always


  postgresdb:
    image: postgres:13
    container_name: postgresdb
    networks:
      - dbNet
      - jaegerNet
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - ./.volumes/pgdata:/var/lib/postgresql/data
    restart: always


  redis-cache:
    image: redis:7.4.1
    container_name: redis-cache
    hostname: redis-cache
    ports:
      - ${REDIS_PORT}
    volumes:
      - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./.volumes/redis:/var/lib/redis
    env_file:
      - ./.env
    networks:
      - notificationsNet
    restart: always


  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander
    env_file:
      - ./.env
    environment:
      - REDIS_HOSTS=redis
    networks:
      - notificationsNet
    ports:
      - ${REDIS_COMMANDER_PORT}
    restart: always


  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
#      - "5775:5775/udp"
#      - "6831:6831/udp"
#      - "6832:6832/udp"
#      - "5778:5778"
      - "16686:16686" # Jaeger UI
#      - "14268:14268" # Jaeger Collector HTTP
      - "14250:14250" # Jaeger gRPC Collector
#      - "9411:9411" # Zipkin compatible endpoint
    environment:
#      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - jaegerNet
    restart: always



networks:
  fcNet:
    name: fcNet
    external: true
    driver: bridge
  dbNet:
    name: dbNet
    driver: bridge
  notificationsNet:
    name: notificationsNet
    driver: bridge
  jaegerNet:
    name: jaegerNet
    driver: bridge