services:
  api-gateway:
    build: ./
#    image: ${ECR_REPOSITORY}/fc-api-gateway:latest
    container_name: api-gateway
    ports:
      - "4081:4081"
    expose:
      - "4081"
    networks:
      - fcNet
      - dbNet
      - jaegerNet
      - notificationsNet
    env_file:
      - ./.env
    environment:
      - OTEL_SERVICE_NAME=api-gateway
      - SPRING_PROFILES_ACTIVE=docker
      - OTEL_TRACES_EXPORTER=${OTEL_TRACES_EXPORTER}
      - OTEL_METRICS_EXPORTER=${OTEL_METRICS_EXPORTER}
      - OTEL_LOGS_EXPORTER=${OTEL_LOGS_EXPORTER}
      - OTEL_METRIC_EXPORT_INTERVAL=${OTEL_METRIC_EXPORT_INTERVAL}
      - TZ=${TIMEZONE}



networks:
  fcNet:
    name: fcNet
    external: true
    driver: bridge
  dbNet:
    name: dbNet
    external: true
    driver: bridge
  notificationsNet:
    name: notificationsNet
    external: true
    driver: bridge
  jaegerNet:
    name: jaegerNet
    external: true
    driver: bridge