#======================================= App Configuration =======================================
spring.application.name=api-gateway
spring.profiles.active=local
spring.main.allow-bean-definition-overriding=true